import { useEffect, useState } from "react";
import { api, type CustomerRisk, type GeneratedCopy } from "../lib/api";

interface Props {
  customer: CustomerRisk;
  businessName: string;
  onClose: () => void;
}

export default function CampaignModal({ customer, businessName, onClose }: Props) {
  const [channel, setChannel] = useState<"email" | "sms">("email");
  const [incentive, setIncentive] = useState("a free week");
  const [copy, setCopy] = useState<GeneratedCopy | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    setCopy(null);
    try {
      setCopy(
        await api.generateCampaign({
          business_name: businessName,
          business_type: "local business",
          customer_name: customer.name,
          channel,
          incentive,
          risk_reasons: customer.reasons,
        })
      );
    } catch (e) {
      setError(e instanceof Error ? e.message : "Generation failed");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    generate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [channel]);

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4"
      onClick={onClose}
    >
      <div
        className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-start justify-between">
          <div>
            <h2 className="text-lg font-semibold">Win back {customer.name}</h2>
            <p className="text-sm text-slate-500">Score {customer.score} · approve before it sends</p>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-700">
            ✕
          </button>
        </div>

        <div className="mt-4 flex gap-2">
          {(["email", "sms"] as const).map((c) => (
            <button
              key={c}
              onClick={() => setChannel(c)}
              className={`rounded-lg px-3 py-1.5 text-sm ${
                channel === c
                  ? "bg-cyan-600 text-white"
                  : "border border-slate-300 text-slate-600"
              }`}
            >
              {c.toUpperCase()}
            </button>
          ))}
          <input
            value={incentive}
            onChange={(e) => setIncentive(e.target.value)}
            placeholder="Incentive (optional)"
            className="flex-1 rounded-lg border border-slate-300 px-3 py-1.5 text-sm"
          />
          <button
            onClick={generate}
            disabled={loading}
            className="rounded-lg border border-slate-300 px-3 py-1.5 text-sm hover:border-slate-400 disabled:opacity-50"
          >
            Regenerate
          </button>
        </div>

        <div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm">
          {loading && <p className="text-slate-400">Generating…</p>}
          {error && <p className="text-red-600">{error}</p>}
          {copy && (
            <>
              {copy.subject && (
                <p className="mb-2 font-medium text-slate-800">Subject: {copy.subject}</p>
              )}
              <p className="whitespace-pre-wrap text-slate-700">{copy.body}</p>
              <p className="mt-3 text-xs text-slate-400">
                {copy.generated_by === "claude"
                  ? `Generated by ${copy.model}`
                  : "Static fallback (set ANTHROPIC_API_KEY for AI copy)"}
              </p>
            </>
          )}
        </div>

        <div className="mt-5 flex justify-end gap-2">
          <button onClick={onClose} className="rounded-lg px-4 py-2 text-sm text-slate-600">
            Cancel
          </button>
          <button
            disabled={!copy}
            className="rounded-lg bg-cyan-600 px-4 py-2 text-sm font-medium text-white hover:bg-cyan-700 disabled:opacity-50"
            onClick={onClose}
          >
            Approve &amp; queue
          </button>
        </div>
      </div>
    </div>
  );
}
