/**
 * Fold the preview build into one self-contained .html file.
 *
 *   npx vite build --config vite.preview.config.ts
 *   node scripts/inline-preview.mjs [outfile]
 *
 * Replaces the <script src> and <link rel=stylesheet> with inline tags so the
 * result opens straight from disk with no sibling files. The Google Fonts
 * @import stays as a network reference — subsetting Spectral and Hanken Grotesk
 * into data URIs would balloon the file, and the page is meant to be viewed
 * online. It falls back to Georgia / system sans offline.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dist = resolve(here, "../.preview-dist");
const out = resolve(process.argv[2] ?? resolve(here, "../../churnary-landing-preview.html"));

for (const f of ["index.html", "bundle.js", "bundle.css"]) {
  if (!existsSync(resolve(dist, f))) {
    console.error(`missing ${f} — run the vite build first`);
    process.exit(1);
  }
}

const html = readFileSync(resolve(dist, "index.html"), "utf8");
const js = readFileSync(resolve(dist, "bundle.js"), "utf8");
const css = readFileSync(resolve(dist, "bundle.css"), "utf8");

// </script> inside the bundle's own string literals would end the tag early.
const safeJs = js.replace(/<\/script>/gi, "<\\/script>");

// Replacer *functions*, not strings: minified JS is full of `$&`, `$'` and `$1`
// sequences, which String.replace interprets as substitution patterns. A string
// replacement silently re-injected the rest of the document (including the
// stylesheet link) wherever the bundle happened to contain `$'`.
let result = html
  .replace(
    /<script type="module"[^>]*src="[^"]*"[^>]*><\/script>/i,
    () => `<script type="module">\n${safeJs}\n</script>`
  )
  .replace(/<link rel="stylesheet"[^>]*href="[^"]*"[^>]*>/i, () => `<style>\n${css}\n</style>`);

if (result.includes("bundle.js") || result.includes("bundle.css")) {
  console.error("inlining failed — an asset reference survived; check the tag patterns");
  process.exit(1);
}

result = result.replace(
  "</head>",
  `  <!-- Self-contained export of the Churnary landing page, for design review.
       Generated by frontend/scripts/inline-preview.mjs — do not hand-edit.
       The waitlist form is stubbed to succeed; there is no backend here. -->
</head>`
);

writeFileSync(out, result, "utf8");
console.log(`wrote ${out} (${Math.round(result.length / 1024)} KB)`);
